#
# Directories
#
OBJDIR ?= .

# Sources and target
SOURCES := mkyaffs2image.c yaffs_ecc.c yaffs_packedtags2.c yaffs_tagsvalidity.c
TARGET  := mkyaffs2img

# Compile flags
CFLAGS += -DCONFIG_YAFFS_UTIL

# Common makefile
include ../common.mk
